Puma_560:
  Link_2:
    mass: 16.847
    inertia:
      ixx: 0.65976
      ixy: 0.000048383
      ixz: 0.0043475
      iyy: 0.59657
      iyz: -0.0000078848
      izz: 0.09723
    origin:
      x: -0.068869
      y: -0.000046775
      z: 0.082737
      roll: 0
      pitch: 0
      yaw: 0
